### ISSUE TITLE
Load Time

### ISSUE THREAD

**Issue by vishaldeshai** [AssistoLab/DropDown#131]
Hello,

I have 9000+ Product and showing dropdown but it takes time.
is there any reason?

thanks in advance.

**Comment by kevin-hirsch** [comment]
Hello @vishaldeshai 👋 

Could you be more precise on what problem you encounter, please?

You are trying to show a drop down with 9000+ choices and it takes too long when the drop down should display itself?

**Comment by vishaldeshai** [comment]
Yes.

But i resolved the problem using following codes.

fileprivate func fittingWidth() -> CGFloat {
		if templateCell == nil {
			templateCell = cellNib.instantiate(withOwner: nil, options: nil)[0] as! DropDownCell
		}
		
		var maxWidth: CGFloat = 0
		
//		for index in 0..<dataSource.count {
//			configureCell(templateCell, at: index)
//			templateCell.bounds.size.height = cellHeight
//			let width = templateCell.systemLayoutSizeFitting(UILayoutFittingCompressedSize).width
//			
//			if width > maxWidth {
//				maxWidth = width
//			}
//		}
		
		return cellHeight
	}

**Comment by kevin-hirsch** [comment]
Actually, `fittingWidth()` is used to dynamically size the width of the drop down so that the width is as wide as the largest label in the drop down.
You can bypass `fittingWidth()` by setting the drop down `width` property, which sets a defined width.

Try doing `dropDown.width = 200` for example. 
Remove the changes you did above in `DropDown` code.
And it should work 👍

**Comment by vishaldeshai** [comment]
my product list is about 9000+ and you are calculating dynamic width using following code:
for index in 0..<dataSource.count
so it is calculating 9000+ times, no need to change in code because my dropdown width is same as my button width and button width will be increased as device width change.

**Comment by kevin-hirsch** [comment]
Yes, but when you have an anchor view, `fittingWidth()` is still called for cases like below:
![screen shot 2017-11-27 at 14 03 35](https://user-images.githubusercontent.com/2794684/33268034-ea2aa936-d37b-11e7-9d38-39912db2622f.png)

So if you want to avoid calling `fittingWidth()`, you'll have to use `DropDown.width` property to set a fixed width.

As a workaround, in your view controller where you have access to your button, try doing this:

```
override func viewDidLayoutSubviews() {
	super.viewDidLayoutSubviews()

	// Will be called once autolayout computes when the view is created
	// And each time the bounds of the views are changed (e.g. screen rotation)
	myDropDown.width = myButton.bounds.width
}
```

Or if the code is in a view, you can override `layoutSublayersOfLayer(layer: CALayer)` instead of `viewDidLayoutSubviews` ;)
