### ISSUE TITLE
Corner Radius Issue

### ISSUE THREAD

**Issue by mdilaveroglu** [AssistoLab/DropDown#192]
```
DropDown.appearance().cornerRadius = 8
```

This piece of code gives `Ambiguous use of 'cornerRadius'` error.

**Comment by mitchclevertronics** [comment]
https://stackoverflow.com/questions/52491806/ambiguous-use-in-xcode-10-swift-4-2/52492230#52492230

**Comment by iwb-kevin-hirsch** [comment]
Hey @mdilaveroglu 👋 

Does the compiler tells you where the ambiguity comes from?
It is possible if you have already in your code or another library this code:

```swift
extension UIView {
   var cornerRadius: CGFloat {
      get {
         return layer.cornerRadius
      }
      set {
         layer.cornerRadius = newValue
      }
   }
}
```

Then this would conflict with `DropDown.cornerRadius` computed variable

Could you try adding the DropDown class the following code:

```
/**
Alias method for `cornerRadius` variable. Use this one instead of `cornerRadius` for non ambiguity.
*/
@objc public dynamic func setupCornerRadius(_ radius: CGFloat) {
	tableViewContainer.layer.cornerRadius = radius
	tableView.layer.cornerRadius = radius
	reloadAllComponents()
}
```

and call `dropDown.setupCornerRadius` function instead of `dropDown.cornerRadius`

Tell me if this fixes your problem and I'll make an update 😉

Thanks 🙏

**Comment by kevin-hirsch** [comment]
Hey @mdilaveroglu 👋 

Does the compiler tells you where the ambiguity comes from?
It is possible if you have already in your code or another library this code:

```swift
extension UIView {
   var cornerRadius: CGFloat {
      get {
         return layer.cornerRadius
      }
      set {
         layer.cornerRadius = newValue
      }
   }
}
```

Then this would conflict with `DropDown.cornerRadius` computed variable

Could you try adding the DropDown class the following code:

```
/**
Alias method for `cornerRadius` variable. Use this one instead of `cornerRadius` for non ambiguity.
*/
@objc public dynamic func setupCornerRadius(_ radius: CGFloat) {
	tableViewContainer.layer.cornerRadius = radius
	tableView.layer.cornerRadius = radius
	reloadAllComponents()
}
```

and call `DropDown.appearance().setupCornerRadius(4)` instead of `dropDown.cornerRadius = 4`

Tell me if this fixes your problem and I'll make an update 😉

Thanks 🙏

**Comment by mdilaveroglu** [comment]
I do have that extension in my project. But calling`setupCornerRadius` causes `[_UIAppearance setupCornerRadius:]: unrecognized selector sent to instance` exception.

**Comment by kevin-hirsch** [comment]
That's normal, you need to open `DropDown.swift` file and add this manually:

```swift
/**
Alias method for `cornerRadius` variable. Use this one instead of `cornerRadius` for non ambiguity.
*/
@objc public dynamic func setupCornerRadius(_ radius: CGFloat) {
	tableViewContainer.layer.cornerRadius = radius
	tableView.layer.cornerRadius = radius
	reloadAllComponents()
}
```

If it still doesn't work, try to clean before building 😉

**Comment by kevin-hirsch** [comment]
Great! Thanks for your help 🙏
DropDown 2.3.6 is now available with the `setupCornerRadius` function 🚀
And I've mentioned at the bottom of the README the issue

**Comment by linhVmodev** [comment]
Use `setupCornerRadius` will not help if `func setupUI` run after it
