### ISSUE TITLE
How to avoid double tap on button that fires drop down.

### ISSUE THREAD

**Issue by Said13** [AssistoLab/DropDown#205]
I need to know when drop down is shown or not shown to avoid double tap on button that opens drop down. Can you please provide checked like isShowingNow? Or something like this.

**Comment by Said13** [comment]
@kevin-hirsch hey man, we really need this feature. please, provide as soon as posible

**Comment by kevin-hirsch** [comment]
Hello @Said13 👋

No need to rush, you're always welcomed to do a pull request 😉
But for the case you mention, you shouldn't have any problem:
calling `dropDown.show()` on a `dropDown` which is already displayed shouldn't do anything 😉
Now if you really need to now if the `dropDown` is displayed already, since it's a `UIView` you can use:
- `dropDown.isHidden` property
- `dropDown.alpha = 0`
- `DropDown.VisibleDropDown == myDropDown`

**Comment by Said13** [comment]
@kevin-hirsch , thank you for your fast feedback. Well, it should not, but actualy `willShowAction` is happening even if `dropDown` is already displayed.

**Comment by kevin-hirsch** [comment]
I see the problem. A workaround would be to move the code you put in the `willShowAction` next to where you call `dropDown.show()`
