### ISSUE TITLE
Could not load NIB in bundle: 'NSBundle with name 'DropDownCell'

### ISSUE THREAD

**Issue by tulioht** [AssistoLab/DropDown#23]
GAIUncaughtExceptionHandler(NSException *) (GAIUncaughtExceptionHandler.m:48): Uncaught exception: Could not load NIB in bundle: 'NSBundle </Users/tuliothome/Library/Developer/Xcode/DerivedData/iOSFanfics-enerleptowspyagorhkcphtttefg/Build/Products/Debug-iphonesimulator/DropDown.framework> (loaded)' with name 'DropDownCell'

**Comment by kevin-hirsch** [comment]
Hello @tulioht, which version of `DropDown` are you using?

**Comment by tulioht** [comment]
DropDown Version 1.0
Installed by CocoaPods 1.0.1

**Comment by kevin-hirsch** [comment]
Thanks. I will try this and get back to you today (Belgian time) ;)

**Comment by kevin-hirsch** [comment]
Okay, first, from what I can see, you have to declare the `dropDown` outside of this function, otherwise it will be released at the end of the function because nothing is retaining it. Move `let dropDown = DropDown()` to a view controller property.

**Comment by tulioht** [comment]
Thanks, worked

Just do not understand why it has to be global

**Comment by kevin-hirsch** [comment]
The `DropDown` is like any variable, so it's like:

```swift
func function() {
   var a: Int = 0 // Declaration
   a += 2
} // Here, a is not retained outside the function so it will be released
```

It's the same for the `DropDown` because when you set an `anchorView`, this `anchorView` does not retain the `DropDown` (not added as a direct subview). And since the `DropDown` is not yet retained by some view hierarchy (or even if it will be, when `DropDown` is hidden, it is removed from view hierarchy), it is released.
